# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('credentials', models.CharField(blank=True, max_length=50)),
                ('word', models.CharField(max_length=10)),
                ('acronym', models.CharField(blank=True, max_length=10)),
                ('definition', models.CharField(max_length=30)),
                ('links', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
